export const GET_SCREENS_REQUEST = 'GET_SCREENS_REQUEST'
export const GET_SCREENS_SUCCESS = 'GET_SCREENS_SUCCESS'
export const GET_APPS_REQUEST = 'GET_APPS_REQUEST'
export const GET_APPS_SUCCESS = 'GET_APPS_SUCCESS'
export const TAP_URL = 'http://api.tappawards.com/api/v1'